<x-app-layout>
    <x-slot name="title">Approval Pengawas {{ $logbook->logbook_number }}</x-slot>
    <div class="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><a href="{{ $isPending ? route('department-operation.approvals.pending') : route('department-operation.approvals.history') }}" class="text-xs font-bold text-[#00A859] hover:underline">← Kembali</a><h1 class="text-2xl font-bold text-slate-800 mt-2">Approval Pengawas · {{ $logbook->logbook_number }}</h1><p class="text-xs text-slate-500 mt-1">Trainee: {{ $logbook->trainee->name }} · {{ $logbook->trainee->nrp }}</p></div><x-badge :status="$logbook->status" /></div>
    <div class="grid grid-cols-1 xl:grid-cols-5 gap-6" x-data="{ action: 'approve' }">
        <div class="xl:col-span-2 space-y-5">
            <section class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><div class="flex items-center justify-between"><h2 class="text-sm font-bold text-slate-800">Submitted Logbook</h2><span class="text-[10px] font-bold text-slate-400 uppercase">Read only</span></div><dl class="mt-4 grid grid-cols-2 gap-4 text-xs"><div><dt class="text-slate-400">Tanggal / Shift</dt><dd class="font-semibold mt-1">{{ $logbook->date->format('d M Y') }} · {{ ucfirst($logbook->shift) }}</dd></div><div><dt class="text-slate-400">Unit</dt><dd class="font-semibold mt-1">{{ $logbook->unit_code }}</dd></div><div><dt class="text-slate-400">Lokasi</dt><dd class="font-semibold mt-1">{{ $logbook->location }}</dd></div><div><dt class="text-slate-400">Durasi</dt><dd class="font-semibold mt-1">{{ $logbook->total_hm }} HM</dd></div><div><dt class="text-slate-400">Trainer</dt><dd class="font-semibold mt-1">{{ $logbook->trainer->name ?? '-' }}</dd></div><div><dt class="text-slate-400">Dikirim Trainee</dt><dd class="font-semibold mt-1">{{ optional($logbook->submitted_at)->format('d M Y H:i') ?? '-' }}</dd></div></dl></section>
            <section class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><h2 class="text-sm font-bold text-slate-800">Aktivitas Harian</h2><p class="mt-3 whitespace-pre-line text-xs text-slate-600 leading-relaxed">{{ $logbook->daily_activity }}</p></section>
            <section class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><h2 class="text-sm font-bold text-slate-800">Bukti Pendukung</h2><div class="mt-3 space-y-2">@forelse($logbook->evidences as $evidence)<a href="{{ asset('storage/'.$evidence->file_path) }}" target="_blank" class="block text-xs text-[#00593E] font-semibold p-3 bg-emerald-50 rounded-lg">{{ $evidence->file_name }} <span class="text-slate-400 font-normal">· {{ $evidence->file_size }}</span></a>@empty <p class="text-xs text-amber-700 bg-amber-50 p-3 rounded-lg">Tidak ada bukti pendukung yang dilampirkan.</p>@endforelse</div></section>
        </div>
        <div class="xl:col-span-3 space-y-5">
            @php $evaluation = $logbook->evaluation; $criteria = ['safety' => 'Penerapan K3 & Golden Rules', 'operation' => 'Pengoperasian Unit', 'procedure' => 'Kepatuhan SOP', 'communication' => 'Komunikasi Operasional']; $scores = $evaluation?->assessment_payload ?? []; @endphp
            <section class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div class="p-5 bg-[#003829] text-white"><p class="text-emerald-300 text-[10px] uppercase font-bold tracking-widest">Read-only · Trainer Evaluation</p><h2 class="font-bold mt-1">Evaluasi Kompetensi Trainer</h2><p class="text-xs text-emerald-100 mt-1">Diverifikasi {{ optional($logbook->verified_at)->format('d M Y, H:i') ?? '-' }}.</p></div><div class="p-5"><div class="grid sm:grid-cols-2 gap-3">@foreach($criteria as $key => $label)<div class="rounded-xl border border-slate-200 p-3"><p class="text-[11px] text-slate-500">{{ $label }}</p><p class="mt-1 text-sm font-bold text-slate-800">{{ $scores[$key] ?? '-' }} / 4</p></div>@endforeach</div><div class="mt-4 grid sm:grid-cols-2 gap-4 text-xs"><div class="rounded-xl bg-emerald-50 p-4"><p class="text-emerald-700 font-bold">Status Kompetensi</p><p class="mt-1 text-emerald-950">{{ $evaluation?->competency_status === 'competent' ? 'Kompeten' : 'Belum Kompeten' }} · Skor {{ $evaluation?->overall_score ?? '-' }}/100</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-slate-500 font-bold">Komentar Trainer</p><p class="mt-1 text-slate-700 whitespace-pre-line">{{ $evaluation?->trainer_comment ?: 'Tidak ada komentar.' }}</p></div></div></div></section>

            @if($isPending)
                @include('department-operation.approvals.partials.decision-form')
            @else
                <section class="rounded-2xl border {{ in_array($logbook->status, ['approved', 'supervisor_approved', 'final_approved'], true) ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50' }} p-5"><p class="text-xs font-bold {{ in_array($logbook->status, ['approved', 'supervisor_approved', 'final_approved'], true) ? 'text-emerald-900' : 'text-amber-900' }}">Keputusan Pengawas · {{ optional($logbook->pjo_decided_at)->format('d M Y, H:i') }}</p><p class="mt-2 text-xs text-slate-700 whitespace-pre-line">{{ $logbook->pjo_notes ?: 'Tidak ada catatan keputusan.' }}</p><p class="mt-3 text-[11px] text-slate-500">Diputuskan oleh {{ $logbook->departmentOperation->name ?? 'Pengawas' }}</p>@if($logbook->pjo_signature_path)<img src="{{ asset('storage/'.$logbook->pjo_signature_path) }}" alt="Signature pengawas" class="mt-4 max-h-20 w-auto object-contain bg-white rounded-lg border border-emerald-200 p-2">@endif</section>
            @endif
        </div>
    </div>
</x-app-layout>
