<?php
    $payload = $logbook->sop_payload ?? [];
    $family = data_get($payload, 'meta.unit_family');
    $checklist = data_get($payload, $family, []);
?>

<form method="POST" action="<?php echo e(route('trainer.reviews.checklist.update', $logbook->id)); ?>" class="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <?php echo csrf_field(); ?>
    <?php echo method_field('PUT'); ?>
    <div class="mb-4"><h2 class="text-sm font-bold text-slate-800">Edit Checklist K / BK</h2><p class="mt-1 text-[11px] text-slate-500">Trainer dapat mengoreksi pilihan K atau BK sebelum approval.</p></div>
    <?php $__currentLoopData = data_get($checklist, 'groups', []); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $groupIndex => $group): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <div class="mb-5 overflow-hidden rounded-xl border border-slate-200">
            <div class="bg-[#003829] px-4 py-3 text-xs font-bold uppercase text-white"><?php echo e($group['title'] ?? 'Checklist'); ?></div>
            <div class="overflow-x-auto"><table class="min-w-[760px] w-full table-fixed text-xs"><colgroup><col class="w-20"><col><col class="w-16"><col class="w-16"><col class="w-80"></colgroup><thead class="bg-slate-50 text-slate-500"><tr><th class="p-3 text-left">No</th><th class="p-3 text-left">Item Evaluasi</th><th class="p-3 text-center">K</th><th class="p-3 text-center">BK</th><th class="p-3 text-left">Catatan Penguji</th></tr></thead><tbody class="divide-y divide-slate-100"><?php $__currentLoopData = $group['items'] ?? []; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $itemIndex => $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="p-3 font-bold align-middle"><?php echo e($item['code'] ?? ($itemIndex + 1)); ?></td><td class="p-3 leading-relaxed align-middle"><?php echo e($item['label'] ?? '-'); ?></td><td class="p-3 text-center align-middle"><input required type="radio" name="checklist[groups][<?php echo e($groupIndex); ?>][items][<?php echo e($itemIndex); ?>][status]" value="K" <?php if(($item['status'] ?? '') === 'K'): echo 'checked'; endif; ?>></td><td class="p-3 text-center align-middle"><input type="radio" name="checklist[groups][<?php echo e($groupIndex); ?>][items][<?php echo e($itemIndex); ?>][status]" value="BK" <?php if(($item['status'] ?? '') === 'BK'): echo 'checked'; endif; ?>></td><td class="p-3 align-middle"><input name="checklist[groups][<?php echo e($groupIndex); ?>][items][<?php echo e($itemIndex); ?>][note]" value="<?php echo e($item['note'] ?? ''); ?>" class="w-full rounded border-slate-300 text-xs"></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div>
        </div>
    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    <?php if(data_get($checklist, 'behavior')): ?>
        <div class="mb-5 overflow-hidden rounded-xl border border-slate-200"><div class="bg-[#003829] px-4 py-3 text-xs font-bold uppercase text-white">Kedisiplinan dan Komunikasi</div><div class="overflow-x-auto"><table class="min-w-[760px] w-full table-fixed text-xs"><colgroup><col class="w-20"><col><col class="w-16"><col class="w-16"><col class="w-80"></colgroup><thead class="bg-slate-50 text-slate-500"><tr><th class="p-3 text-left">No</th><th class="p-3 text-left">Item Evaluasi</th><th class="p-3 text-center">K</th><th class="p-3 text-center">BK</th><th class="p-3 text-left">Catatan Penguji</th></tr></thead><tbody class="divide-y divide-slate-100"><?php $__currentLoopData = data_get($checklist, 'behavior', []); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $itemIndex => $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="p-3 font-bold align-middle"><?php echo e($item['code'] ?? ($itemIndex + 1)); ?></td><td class="p-3 leading-relaxed align-middle"><?php echo e($item['label'] ?? '-'); ?></td><td class="p-3 text-center align-middle"><input required type="radio" name="checklist[behavior][<?php echo e($itemIndex); ?>][status]" value="K" <?php if(($item['status'] ?? '') === 'K'): echo 'checked'; endif; ?>></td><td class="p-3 text-center align-middle"><input type="radio" name="checklist[behavior][<?php echo e($itemIndex); ?>][status]" value="BK" <?php if(($item['status'] ?? '') === 'BK'): echo 'checked'; endif; ?>></td><td class="p-3 align-middle"><input name="checklist[behavior][<?php echo e($itemIndex); ?>][note]" value="<?php echo e($item['note'] ?? ''); ?>" class="w-full rounded border-slate-300 text-xs"></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div></div>
    <?php endif; ?>
    <div class="flex justify-end"><button class="rounded-xl bg-[#003829] px-5 py-3 text-xs font-bold text-white">Simpan Checklist</button></div>
</form>
<?php /**PATH D:\KULIAH\BERAU COAL INTERN\logbook\resources\views/trainer/reviews/partials/checklist-editor.blade.php ENDPATH**/ ?>