<?php ($reviewer = auth()->user()); ?>
<section class="mt-8 bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden" x-data="{ action: '<?php echo e(old('action', 'approve')); ?>' }">
    <div class="bg-[#003829] px-6 py-4 text-white"><p class="text-[10px] font-bold uppercase tracking-widest text-emerald-300">Keputusan Kabag Training Centre</p><h2 class="mt-1 text-sm font-bold">Final Approval atau Permintaan Revisi</h2></div>
    <?php if($isPending): ?>
        <form method="POST" action="<?php echo e(route('training-centre.approvals.decide', $logbook->id)); ?>" class="p-6 space-y-5"><?php echo csrf_field(); ?>
            <div class="grid gap-5 lg:grid-cols-2"><label class="block rounded-xl border border-emerald-200 bg-emerald-50 p-5 cursor-pointer"><span class="flex items-center gap-2 text-xs font-bold text-[#00593E]"><input type="radio" name="action" value="approve" x-model="action"> Setujui & Finalisasi Dokumen</span><span class="mt-2 block text-[11px] leading-relaxed text-emerald-800">Tanda tangan profil akan dipakai otomatis saat final approval.</span><?php if($reviewer?->signature_path): ?><img src="<?php echo e(asset('storage/'.$reviewer->signature_path)); ?>" alt="Signature profile" class="mt-4 max-h-20 w-auto object-contain bg-white rounded-lg border border-emerald-200 p-2"><?php else: ?><div class="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-[11px] text-amber-900">Simpan tanda tangan dulu di <a href="<?php echo e(route('profile.edit')); ?>" class="font-bold underline">My Profile</a> sebelum final approval.</div><?php endif; ?></label><label class="block rounded-xl border border-amber-200 bg-amber-50 p-5 cursor-pointer"><span class="flex items-center gap-2 text-xs font-bold text-amber-900"><input type="radio" name="action" value="revision" x-model="action"> Kembalikan untuk Revisi</span><span class="mt-2 block text-[11px] leading-relaxed text-amber-800">Logbook dikembalikan ke Trainee untuk perbaikan.</span><textarea name="approval_notes" rows="3" class="mt-4 w-full rounded-lg border-amber-300 text-xs" placeholder="Tuliskan instruksi revisi..." :disabled="action !== 'revision'"><?php echo e(old('approval_notes')); ?></textarea></label></div><?php if($errors->any()): ?><p class="text-xs text-rose-600"><?php echo e($errors->first()); ?></p><?php endif; ?>
            <div><label class="text-xs font-bold text-slate-700">Catatan Kabag <span class="font-normal text-slate-400">(opsional)</span></label><textarea name="approval_notes" rows="3" class="mt-2 w-full rounded-xl border-slate-300 text-xs" placeholder="Masukkan catatan final..." :disabled="action === 'revision'"><?php echo e(old('approval_notes')); ?></textarea></div><div class="flex justify-end"><button class="rounded-xl bg-[#00A859] px-5 py-3 text-xs font-bold text-white hover:bg-emerald-600">Simpan Keputusan</button></div>
        </form>
    <?php else: ?>
        <div class="p-6"><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-900"><p class="font-bold">Dokumen telah mendapatkan final approval Training Centre.</p><p class="mt-2 whitespace-pre-line"><?php echo e($logbook->training_centre_notes ?: 'Tidak ada catatan final.'); ?></p><a href="<?php echo e(route('ojt.logbooks.print', $logbook->id)); ?>" target="_blank" class="mt-4 inline-flex rounded-lg bg-[#003829] px-4 py-2 font-bold text-white">Download / Cetak Arsip</a></div></div>
    <?php endif; ?>
</section>
<?php /**PATH D:\KULIAH\BERAU COAL INTERN\logbook\resources\views/training-centre/approvals/partials/decision-form.blade.php ENDPATH**/ ?>