<x-app-layout>
    <x-slot name="title">Dashboard Pengawas</x-slot>
    <div class="mb-8 bg-gradient-to-r from-[#003829] to-[#00593E] p-6 rounded-2xl shadow-md text-white border border-emerald-900 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div><p class="text-emerald-300 text-xs font-bold uppercase tracking-widest mb-1">Department Operation · Pengawas</p><h1 class="text-2xl font-bold">Dashboard Approval Pengawas</h1><p class="text-emerald-100 text-xs mt-1">Final review atas logbook dan evaluasi kompetensi yang telah diverifikasi Trainer.</p></div>
        <div class="rounded-xl bg-white/10 border border-white/15 px-4 py-3 text-xs"><p class="text-emerald-200">Pengawas Operasional</p><p class="font-bold mt-0.5">{{ $operator->name }} · {{ $operator->nrp }}</p></div>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-5 mb-7">
        @foreach([['Menunggu Persetujuan', $kpi['pending'], 'blue'], ['Disetujui Bulan Ini', $kpi['approved_this_month'], 'emerald'], ['Dikembalikan Bulan Ini', $kpi['returned_this_month'], 'amber']] as [$label, $value, $color])
            <div class="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-{{ $color }}-600">{{ $label }}</p><p class="mt-2 text-3xl font-extrabold text-slate-800">{{ $value }}</p></div>
        @endforeach
    </div>
    <div class="grid grid-cols-1 xl:grid-cols-2 gap-6">
        <section class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div class="p-5 border-b border-slate-100 flex justify-between items-center"><div><h2 class="font-bold text-slate-800">Antrean Prioritas</h2><p class="text-xs text-slate-500 mt-1">Hasil evaluasi Trainer yang siap disetujui.</p></div><a href="{{ route('department-operation.approvals.pending') }}" class="text-xs font-bold text-[#00A859]">Lihat semua</a></div><div class="divide-y divide-slate-100">@forelse($pendingLogbooks as $logbook)<a href="{{ route('department-operation.approvals.show', $logbook->id) }}" class="block px-5 py-4 hover:bg-emerald-50/40"><div class="flex justify-between gap-3"><div><p class="text-xs font-bold text-slate-800">{{ $logbook->logbook_number }}</p><p class="text-[11px] text-slate-500 mt-1">{{ $logbook->trainee->name }} · {{ $logbook->equipment->unit_code ?? '-' }}</p></div><span class="text-[11px] text-slate-500">{{ optional($logbook->verified_at)->format('d M Y') }}</span></div></a>@empty <p class="px-5 py-10 text-center text-sm text-slate-400">Tidak ada antrean persetujuan.</p>@endforelse</div></section>
        <section class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div class="p-5 border-b border-slate-100 flex justify-between items-center"><div><h2 class="font-bold text-slate-800">Keputusan Terbaru</h2><p class="text-xs text-slate-500 mt-1">Riwayat keputusan Pengawas.</p></div><a href="{{ route('department-operation.approvals.history') }}" class="text-xs font-bold text-[#00A859]">Lihat riwayat</a></div><div class="divide-y divide-slate-100">@forelse($recentApprovals as $logbook)<a href="{{ route('department-operation.approvals.show', $logbook->id) }}" class="block px-5 py-4 hover:bg-emerald-50/40"><div class="flex justify-between gap-3"><div><p class="text-xs font-bold text-slate-800">{{ $logbook->logbook_number }}</p><p class="text-[11px] text-slate-500 mt-1">{{ $logbook->trainee->name }} · {{ optional($logbook->pjo_decided_at)->format('d M Y, H:i') }}</p></div><x-badge :status="$logbook->status" /></div></a>@empty <p class="px-5 py-10 text-center text-sm text-slate-400">Belum ada keputusan yang dibuat.</p>@endforelse</div></section>
    </div>
</x-app-layout>
