<x-app-layout>
    <x-slot name="title">Review {{ $logbook->logbook_number }}</x-slot>
    <div class="mb-4 sm:mb-6 flex items-center justify-between flex-wrap gap-3"><div><a href="{{ route('trainer.reviews.index') }}" class="text-xs font-bold text-[#2563eb] hover:underline">← Kembali ke antrean</a><h1 class="text-lg sm:text-2xl font-bold text-slate-800 mt-1 sm:mt-2">Review {{ $logbook->logbook_number }}</h1><p class="text-[10px] sm:text-xs text-slate-500 mt-1">Trainee: {{ $logbook->trainee->name }} · {{ $logbook->trainee->sid }}</p></div><x-badge :status="$logbook->status" /></div>
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6" x-data="{ action: 'verify' }">
        <div class="lg:col-span-2 space-y-4 sm:space-y-5">
            <div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-4 sm:p-5"><h2 class="text-xs sm:text-sm font-bold text-slate-800">Ringkasan Operasional</h2><dl class="mt-3 sm:mt-4 grid grid-cols-2 gap-3 sm:gap-4 text-xs"><div><dt class="text-slate-400">Tanggal / Shift</dt><dd class="font-semibold mt-1">{{ $logbook->date->format('d M Y') }} · {{ ucfirst($logbook->shift) }}</dd></div><div><dt class="text-slate-400">Unit</dt><dd class="font-semibold mt-1">{{ $logbook->unit_code }}</dd></div><div><dt class="text-slate-400">Lokasi</dt><dd class="font-semibold mt-1">{{ $logbook->location }}</dd></div><div><dt class="text-slate-400">Durasi</dt><dd class="font-semibold mt-1">{{ $logbook->total_hm }} HM</dd></div></dl></div>
        </div>
        <div class="lg:col-span-3"><form method="POST" action="{{ route('trainer.reviews.evaluate', $logbook->id) }}" class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">@csrf
            <div class="p-4 sm:p-5 bg-[#1e3a8a] text-white"><p class="text-[10px] font-bold uppercase font-bold tracking-widest text-blue-300">Form Evaluasi Kompetensi · SOP OJT</p><h2 class="font-bold mt-1 text-sm sm:text-base">Penilaian Trainer</h2><p class="text-[10px] sm:text-xs text-blue-100 mt-1">Skala 1 = perlu bimbingan hingga 4 = mandiri dan konsisten.</p></div>
            <div class="p-4 sm:p-5 space-y-4 sm:space-y-5">
                @php $criteria = ['safety' => ['Penerapan K3 & Golden Rules', 'P2H, APD, hazard awareness, dan disiplin area kerja'], 'operation' => ['Pengoperasian Unit', 'Kontrol unit, produktivitas, dan teknik kerja'], 'procedure' => ['Kepatuhan SOP', 'Urutan kerja, inspeksi, dan dokumentasi'], 'communication' => ['Komunikasi Operasional', 'Koordinasi dengan pengawas, dispatcher, dan tim']]; $payload = $logbook->evaluation->assessment_payload ?? []; @endphp
                @foreach($criteria as $name => [$label, $help])<div class="border border-slate-200 rounded-xl p-4"><div class="flex justify-between gap-3"><div><p class="text-xs font-bold text-slate-800">{{ $label }}</p><p class="text-[11px] text-slate-500 mt-1">{{ $help }}</p></div><select name="{{ $name }}" class="text-xs rounded-lg border-slate-300" @disabled($logbook->status === 'verified')>@for($i=1;$i<=4;$i++)<option value="{{ $i }}" @selected(old($name, $payload[$name] ?? 3) == $i)>{{ $i }} — {{ ['Perlu bimbingan','Cukup','Baik','Sangat baik'][$i-1] }}</option>@endfor</select></div></div>@endforeach
                <div><label class="text-xs font-bold text-slate-700">Komentar Trainer</label><textarea name="trainer_comment" rows="3" class="mt-2 w-full text-xs rounded-xl border-slate-300" @disabled($logbook->status === 'verified') placeholder="Umpan balik spesifik atas performa trainee...">{{ old('trainer_comment', $logbook->evaluation->trainer_comment ?? '') }}</textarea></div>
                @if($logbook->status !== 'verified')<div class="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4"><div><label class="text-xs font-bold text-slate-700">Keputusan Kompetensi</label><select name="competency_status" class="mt-2 w-full text-xs rounded-xl border-slate-300 min-h-[44px]"><option value="competent">Kompeten</option><option value="not_yet_competent">Belum Kompeten</option></select></div><div class="flex items-end pb-2"><label class="flex gap-2 items-start text-xs text-slate-600"><input type="checkbox" name="send_to_pjo" value="1" class="rounded text-[#2563eb] mt-0.5"><span><b>Kirim hasil ke PJO</b><br><span class="text-slate-400">Hanya untuk evaluasi yang diverifikasi.</span></span></label></div></div>
                <div class="bg-amber-50 border border-amber-200 rounded-xl p-4"><label class="flex items-center gap-2 text-xs font-bold text-amber-900"><input type="radio" name="action" value="revision" x-model="action"> Minta Revisi dari Trainee</label><textarea name="revision_instruction" x-show="action === 'revision'" x-cloak rows="3" class="mt-3 w-full text-xs rounded-lg border-amber-300" placeholder="Jelaskan revisi yang wajib dilakukan...">{{ old('revision_instruction') }}</textarea></div>
                <label class="flex items-center gap-2 text-xs font-bold text-[#1d4ed8]"><input type="radio" name="action" value="verify" x-model="action" checked> Verifikasi & finalisasi evaluasi</label>
                <div class="flex flex-col sm:flex-row justify-end gap-2 sm:gap-3">
                    <a href="{{ route('trainer.reviews.index') }}" class="px-4 sm:px-5 py-2.5 sm:py-3 rounded-xl border border-slate-300 text-xs font-bold text-slate-600 hover:bg-slate-50 transition text-center min-h-[44px] inline-flex items-center justify-center">
                        Batal
                    </a>
                    <button type="submit" class="px-4 sm:px-5 py-2.5 sm:py-3 rounded-xl bg-[#2563eb] hover:bg-blue-600 text-white text-xs font-bold transition min-h-[44px]">Simpan Evaluasi</button>
                </div>@else <div class="rounded-xl bg-amber-50 border border-amber-200 p-4 text-xs text-amber-900"><b>Evaluasi final:</b> {{ $logbook->evaluation->competency_status === 'competent' ? 'Kompeten' : 'Belum Kompeten' }} · Skor {{ $logbook->evaluation->overall_score }}/100 @if($logbook->evaluation->sent_to_pjo_at)<br><span class="text-amber-700">Hasil sudah dikirim ke PJO pada {{ $logbook->evaluation->sent_to_pjo_at->format('d M Y H:i') }}.</span>@endif</div>@endif
                @if($errors->any())<p class="text-xs text-red-600">{{ $errors->first() }}</p>@endif
            </div>
        </form></div>
    </div>
</x-app-layout>


