<x-app-layout>
    <x-slot name="title">Review {{ $logbook->logbook_number }}</x-slot>
    <div class="mb-6 flex items-center justify-between"><div><a href="{{ route('trainer.reviews.index') }}" class="text-xs font-bold text-[#00A859] hover:underline">← Kembali ke antrean</a><h1 class="text-2xl font-bold text-slate-800 mt-2">Review {{ $logbook->logbook_number }}</h1><p class="text-xs text-slate-500 mt-1">Trainee: {{ $logbook->trainee->name }} · {{ $logbook->trainee->nrp }}</p></div><x-badge :status="$logbook->status" /></div>
    <div class="grid grid-cols-1 xl:grid-cols-5 gap-6" x-data="{ action: 'verify' }">
        <div class="xl:col-span-2 space-y-5">
            <div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><h2 class="text-sm font-bold text-slate-800">Ringkasan Operasional</h2><dl class="mt-4 grid grid-cols-2 gap-4 text-xs"><div><dt class="text-slate-400">Tanggal / Shift</dt><dd class="font-semibold mt-1">{{ $logbook->date->format('d M Y') }} · {{ ucfirst($logbook->shift) }}</dd></div><div><dt class="text-slate-400">Unit</dt><dd class="font-semibold mt-1">{{ $logbook->equipment->unit_code ?? '-' }}</dd></div><div><dt class="text-slate-400">Lokasi</dt><dd class="font-semibold mt-1">{{ $logbook->location }}</dd></div><div><dt class="text-slate-400">Durasi</dt><dd class="font-semibold mt-1">{{ $logbook->total_hm }} HM</dd></div></dl></div>
            <div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><h2 class="text-sm font-bold text-slate-800">Aktivitas Harian</h2><p class="mt-3 whitespace-pre-line text-xs text-slate-600 leading-relaxed">{{ $logbook->daily_activity }}</p></div>
            <div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><h2 class="text-sm font-bold text-slate-800">Bukti Pendukung</h2><div class="mt-3 space-y-2">@forelse($logbook->evidences as $evidence)<a href="{{ asset('storage/'.$evidence->file_path) }}" target="_blank" class="block text-xs text-[#00593E] font-semibold p-3 bg-emerald-50 rounded-lg">{{ $evidence->file_name }} <span class="text-slate-400 font-normal">· {{ $evidence->file_size }}</span></a>@empty <p class="text-xs text-amber-700 bg-amber-50 p-3 rounded-lg">Tidak ada bukti pendukung yang dilampirkan.</p>@endforelse</div></div>
        </div>
        <div class="xl:col-span-3"><form method="POST" action="{{ route('trainer.reviews.evaluate', $logbook->id) }}" class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">@csrf
            <div class="p-5 bg-[#003829] text-white"><p class="text-emerald-300 text-[10px] uppercase font-bold tracking-widest">Form Evaluasi Kompetensi · SOP OJT</p><h2 class="font-bold mt-1">Penilaian Trainer</h2><p class="text-xs text-emerald-100 mt-1">Skala 1 = perlu bimbingan hingga 4 = mandiri dan konsisten.</p></div>
            <div class="p-5 space-y-5">
                @php $criteria = ['safety' => ['Penerapan K3 & Golden Rules', 'P2H, APD, hazard awareness, dan disiplin area kerja'], 'operation' => ['Pengoperasian Unit', 'Kontrol unit, produktivitas, dan teknik kerja'], 'procedure' => ['Kepatuhan SOP', 'Urutan kerja, inspeksi, dan dokumentasi'], 'communication' => ['Komunikasi Operasional', 'Koordinasi dengan pengawas, dispatcher, dan tim']]; $payload = $logbook->evaluation->assessment_payload ?? []; @endphp
                @foreach($criteria as $name => [$label, $help])<div class="border border-slate-200 rounded-xl p-4"><div class="flex justify-between gap-3"><div><p class="text-xs font-bold text-slate-800">{{ $label }}</p><p class="text-[11px] text-slate-500 mt-1">{{ $help }}</p></div><select name="{{ $name }}" class="text-xs rounded-lg border-slate-300" @disabled($logbook->status === 'verified')>@for($i=1;$i<=4;$i++)<option value="{{ $i }}" @selected(old($name, $payload[$name] ?? 3) == $i)>{{ $i }} — {{ ['Perlu bimbingan','Cukup','Baik','Sangat baik'][$i-1] }}</option>@endfor</select></div></div>@endforeach
                <div><label class="text-xs font-bold text-slate-700">Komentar Trainer</label><textarea name="trainer_comment" rows="3" class="mt-2 w-full text-xs rounded-xl border-slate-300" @disabled($logbook->status === 'verified') placeholder="Umpan balik spesifik atas performa trainee...">{{ old('trainer_comment', $logbook->evaluation->trainer_comment ?? '') }}</textarea></div>
                @if($logbook->status !== 'verified')<div class="grid md:grid-cols-2 gap-4"><div><label class="text-xs font-bold text-slate-700">Keputusan Kompetensi</label><select name="competency_status" class="mt-2 w-full text-xs rounded-xl border-slate-300"><option value="competent">Kompeten</option><option value="not_yet_competent">Belum Kompeten</option></select></div><div class="flex items-end pb-2"><label class="flex gap-2 items-start text-xs text-slate-600"><input type="checkbox" name="send_to_pjo" value="1" class="rounded text-[#00A859] mt-0.5"><span><b>Kirim hasil ke PJO</b><br><span class="text-slate-400">Hanya untuk evaluasi yang diverifikasi.</span></span></label></div></div>
                <div class="bg-amber-50 border border-amber-200 rounded-xl p-4"><label class="flex items-center gap-2 text-xs font-bold text-amber-900"><input type="radio" name="action" value="revision" x-model="action"> Minta Revisi dari Trainee</label><textarea name="revision_instruction" x-show="action === 'revision'" x-cloak rows="3" class="mt-3 w-full text-xs rounded-lg border-amber-300" placeholder="Jelaskan revisi yang wajib dilakukan...">{{ old('revision_instruction') }}</textarea></div>
                <label class="flex items-center gap-2 text-xs font-bold text-[#00593E]"><input type="radio" name="action" value="verify" x-model="action" checked> Verifikasi & finalisasi evaluasi</label>
                <div class="flex justify-end"><button class="px-5 py-3 rounded-xl bg-[#00A859] hover:bg-emerald-600 text-white text-xs font-bold">Simpan Keputusan</button></div>@else <div class="rounded-xl bg-emerald-50 border border-emerald-200 p-4 text-xs text-emerald-900"><b>Evaluasi final:</b> {{ $logbook->evaluation->competency_status === 'competent' ? 'Kompeten' : 'Belum Kompeten' }} · Skor {{ $logbook->evaluation->overall_score }}/100 @if($logbook->evaluation->sent_to_pjo_at)<br><span class="text-emerald-700">Hasil sudah dikirim ke PJO pada {{ $logbook->evaluation->sent_to_pjo_at->format('d M Y H:i') }}.</span>@endif</div>@endif
                @if($errors->any())<p class="text-xs text-red-600">{{ $errors->first() }}</p>@endif
            </div>
        </form></div>
    </div>
</x-app-layout>
